version: "3"
services:
  grpc-server:
    image: grpc-server:latest
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    container_name: grpc-server-service
  grpc-client:
    image: grpc-client:latest
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    container_name: grpc-client-service